### ISSUE TITLE
Software referencing Anki, Login not possible

### ISSUE THREAD

**Issue by xanathon** [digital-dream-labs/oskr-owners-manual#1]
Hello,

I go to vector-setup.ddl.io to get the QSN.

All over the setup software I read "Anki". Also I am asked to login with my Anki account. It looks like nothing of the branding here was corrected.

However, if I try to login with my Anki credentials I only get "Invalid username or password".

first: I think all references to Anki need to be replaced with references to DDL.
second: Why can't I log in? If this is not the correct place to ask it (since it is only the documentation repository), please point me to a correct issue tracker for OSKR.

Thanks.

**Edit:** If I click on the "Create an Anki account" I am only redirected to the main DDL page. That also is very unfortunate and not user friendly or helpful at all.

**Comment by grant-olson** [comment]
Official support request channel is to email oskrsupport@digitaldreamlabs.com . However I'll do my best to help here.

For now to get things moving:

1. Go to the advanced setup CLI as decribed in the section of the manual to install an image on the local area network by unchecking "enable auto-setup flow" when you pair.
2. Issuing the command `logs` from there. It should show a status bar then do a normal Chrome file download at the end of the process.

We ended up throwing up this site late in the process which accounts for the branding. We were using a real CLI tool written in Node.js but failed to realize that the bluetooth libraries were OSX-only and wouldn't work on Windows or Linux. But we didn't want to hold up the release process while sorting that out.

**Comment by kercre123** [comment]
> Official support request channel is to email [oskrsupport@digitaldreamlabs.com](mailto:oskrsupport@digitaldreamlabs.com) . However I'll do my best to help here.
> 
> For now to get things moving:
> 
> 1. Go to the advanced setup CLI as decribed in the section of the manual to install an image on the local area network by unchecking "enable auto-setup flow" when you pair.
> 2. Issuing the command `logs` from there. It should show a status bar then do a normal Chrome file download at the end of the process.
> 
> We ended up throwing up this site late in the process which accounts for the branding. We were using a real CLI tool written in Node.js but failed to realize that the bluetooth libraries were OSX-only and wouldn't work on Windows or Linux. But we didn't want to hold up the release process while sorting that out.

Do you think a site could be put up which brings you to the CLI every time?  This is what I have done at https://wwe.project-victor.org/noflow-devsetup

**Comment by xanathon** [comment]
Thanks. @kercre123 was already quite helpful elsewhere.

That OSKR support is only available via email instead of an issue tracker is highly unfortunate. That way questions will be asked all over again via email instead of just once in a transparent issue tracker were all users can see answers. An issue tracker for OSKR backers would take load off DDL support. Probably a lot.

**Comment by grant-olson** [comment]
The link is actually https://www.project-victor.org/noflow-devsetup/html/main.html Typo is pretty trivial but adding this for the record.

We're happy to point the docs to this link. If you're worried about uptime or keeping the site up, we'd need a copy of the forked code accessible via github to deploy it ourselves. I imagine the fix isn't that hard, but might as well reuse the work project victor has done.

**Comment by kercre123** [comment]
It has had mostly 100 percent uptime. Cert wasn't updating for a while but it should be fixed now. It is being hosted on cloud infrastructure another PV member setup that I just have SFTP/SSH access to.

It's just something set to false in rts.js

**Comment by bussardrobbie** [comment]
Closing issue; new UI is mostly done for Vector Web Setup in a separate repo; will create issue in the proper repo to ensure that we implement Escape Pod styling and branding into Vector Web Setup.
