### ISSUE TITLE
"Unlock.md" Lines 198/199 Not Appearing on Webpage

### ISSUE THREAD

**Issue by bussardrobbie** [digital-dream-labs/oskr-owners-manual#4]
In "Unlock.md", where Steps 6 and 7 are described in the "Connecting to the advanced console interface in Vector Web Setup" section, lines 198 and 199 fail to appear on the webpage. I am unsure of how to resolve this, so marking with issue. Here is the affected text:
```
6. In the emulated terminal session, `wifi-scan` to check that Vector can see your wifi
7. Have Vector connect to your wifi with `wifi-connect ` followed by your Wifi SSID and password
```

**Comment by grant-olson** [comment]
These just aren't on the released version of the manual yet. There is a 'release' branch that includes the latest known good version in case the main branch has problems. We'll get a new release out today.
