### ISSUE TITLE
In "Unlock.md", Line 247 Is Cut Off

### ISSUE THREAD

**Issue by bussardrobbie** [digital-dream-labs/oskr-owners-manual#5]
Line 247 in "unlock.md" appears incomplete and I am unable to decipher what the rest of the sentence is supposed to be to fix personally, so opening issue to make a note and determine original intent of what this sentence should be.

**Comment by grant-olson** [comment]
@randym32 This looks like this was from your pull request. I think maybe you were trying to say it wouldn't show the cloud update Icon for this style of update? Can you confirm what you wanted it to say here or should I just delete the sentence fragment?

**Comment by randym32** [comment]
That is my mistake.  You are correct, that was what I was trying to say.  I will submit a fix
